export const Desserts = [
    {
        id: 1,
        name: 'Beer Brewery',
        price: 38,
        text: "Lörem ipsum askstoppad defaktisk, logokemi. Diastat retos att endomatisk. Geogehet pultvätta, om pneumativ.",
        prescrition: "soda,cream,milk,sugar",
        img: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_474,q_75,w_640/v1/clients/newyorkstate/Blog_Header_640x474_1__a1afb378-98e8-4b5b-9088-33f7b0f27a87.jpg"
    }, {
        id: 2,
        name: 'Burger&Pasta',
        price: 38,
        text: "Lörem ipsum askstoppad defaktisk, logokemi. Diastat retos att endomatisk. Geogehet pultvätta, om pneumativ.",
        prescrition: "soda,cream,milk,sugar",
        img: "https://easyfamilyrecipes.com/wp-content/uploads/2020/01/Cheeseburger-Pasta-Recipe.jpg"
    }, {
        id: 3,
        name: 'Beer Brewery',
        price: 38,
        text: "Lörem ipsum askstoppad defaktisk, logokemi. Diastat retos att endomatisk. Geogehet pultvätta, om pneumativ.",
        prescrition: "soda,cream,milk,sugar",
        img: "https://www.allrecipes.com/thmb/P59TgUCXtQbv69dHRlZduE38xs8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/453291-five-ingredient-ice-cream-Alberta-Rose-4x3-1-4c9ec10ac4ab4e828615e81aa608dd6b.jpg"
    }, {
        id: 4,
        name: 'Beer Brewery',
        price: 38,
        text: "Lörem ipsum askstoppad defaktisk, logokemi. Diastat retos att endomatisk. Geogehet pultvätta, om pneumativ.",
        prescrition: "soda,cream,milk,sugar",
        img: "https://www.theendlessmeal.com/wp-content/uploads/2016/07/strawberry-ice-cream-2.jpg"
    }, {
        id: 5,
        name: 'Beer Brewery',
        price: 38,
        text: "Lörem ipsum askstoppad defaktisk, logokemi. Diastat retos att endomatisk. Geogehet pultvätta, om pneumativ.",
        prescrition: "soda,cream,milk,sugar",
        img: "https://cdn.theatlantic.com/thumbor/aY1PcIjNQsMkOX8TOHNws9qhIXo=/438x0:1563x1125/540x540/media/img/2023/04/0523_WEL_Johns_Ice_Cream_c16X9/original.png"
    }, {
        id: 6,
        name: 'Beer Brewery',
        price: 38,
        text: "Lörem ipsum askstoppad defaktisk, logokemi. Diastat retos att endomatisk. Geogehet pultvätta, om pneumativ.",
        prescrition: "soda,cream,milk,sugar",
        img: ""
    },
]
export const HotDrinks = [
    {
        id: 1,
        name: 'Coffee',
        price: 20,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'coffee beans, hot water, milk, sugar',
        img: 'https://cdn10.bostonmagazine.com/wp-content/uploads/2016/01/warm-latte-mug.jpg',
    },
    {
        id: 2,
        name: 'Tea',
        price: 15,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'tea leaves, hot water, lemon, honey',
        img: 'https://media.istockphoto.com/id/827215724/photo/a-cup-of-freshly-brewed-black-tea-escaping-steam-warm-soft-light-darker-background.jpg?s=612x612&w=0&k=20&c=imnF_AExFoho0c_mkRITlwHxDyG3O-Re_ZEfNxbAKn8=',
    },
    {
        id: 3,
        name: 'Hot Chocolate',
        price: 18,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'cocoa powder, hot milk, whipped cream',
        img: 'https://c.files.bbci.co.uk/1558D/production/_109973478_gettyimages-1070054536.jpg',
    },
    {
        id: 4,
        name: 'Chai Latte',
        price: 22,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'black tea, hot milk, spices, sweetener',
        img: 'https://www.comunicaffe.com/wp-content/uploads/2018/10/Hot-beverage.jpg',
    },
    {
        id: 5,
        name: 'Cappuccino',
        price: 25,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'espresso, hot milk, milk foam',
        img: 'https://bycommonconsent.files.wordpress.com/2021/08/american-heritage-chocolate-aoonx98hdm8-unsplash.jpg',
    },
    {
        id: 6,
        name: 'Matcha Latte',
        price: 28,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'matcha powder, hot water, hot milk, sweetener',
        img: 'https://static.independent.co.uk/s3fs-public/thumbnails/image/2016/02/17/10/coffee-rf-getty.jpg',
    }
]
export const ColdDrinks = [
    {
        id: 1,
        name: 'Iced Coffee',
        price: 22,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'coffee concentrate, ice, milk, sweetener',
        img: 'https://sherebengal.com/wp-content/uploads/2017/09/Masala-cold-drinks.jpg',
    },
    {
        id: 2,
        name: 'Iced Tea',
        price: 18,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'tea leaves, ice, lemon, sweetener',
        img: 'https://coin-a-drink.co.uk/wp-content/uploads/2015/07/cold-ice-lime-drinks-hd-widescreen-wallpapers-.jpg',
    },
    {
        id: 3,
        name: 'Iced Matcha Latte',
        price: 28,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'matcha powder, ice, milk, sweetener',
        img: 'https://cdn.cdnparenting.com/articles/2018/07/361921454-H-1024x700.webp',
    },
    {
        id: 4,
        name: 'Iced Chocolate',
        price: 24,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'chocolate syrup, ice, milk, whipped cream',
        img: 'https://img.jamieoliver.com/home/wp-content/uploads/features-import/2015/07/feature-header.jpg',
    },
    {
        id: 5,
        name: 'Smoothie',
        price: 26,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'fruit, yogurt, ice, sweetener (optional)',
        img: 'https://images.pexels.com/photos/8880742/pexels-photo-8880742.jpeg?cs=srgb&dl=pexels-ron-lach-8880742.jpg&fm=jpg',
    },
    {
        id: 6,
        name: 'Lemonade',
        price: 16,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'lemons, water, sugar, ice',
        img: 'https://www.eatingwell.com/thmb/X4bjnnLYDOvTnMsCqQIFD8C5OJc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/8506413-ab4d1923635a4c96b75fc799e202c4b4.jpg',
    }
]
export const NationalFoods = [
    {
        id: 1,
        name: 'Sushi',
        price: 35,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'rice, fish, seaweed, soy sauce',
        img: 'https://www.allcleartravel.co.uk/wp-content/uploads/2020/09/spaghetti-bolognese-11.jpg',
    },
    {
        id: 2,
        name: 'Tacos',
        price: 30,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'tortillas, meat, vegetables, salsa',
        img: 'https://www.worldatlas.com/r/w1200/upload/b0/9d/b6/shutterstock-642510559.jpg',
    },
    {
        id: 3,
        name: 'Pizza',
        price: 25,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'dough, tomato sauce, cheese, toppings',
        img: 'https://cdn.theatlantic.com/thumbor/DlYmhxftrgbsC16XEL74Md3bVbE=/1x0:3701x2081/1600x900/media/img/mt/2022/02/Foodnations_01/original.jpg',
    },
    {
        id: 4,
        name: 'Pad Thai',
        price: 28,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'rice noodles, shrimp, tofu, peanuts',
        img: 'https://i0.wp.com/nationalfoods.org/wp-content/uploads/2017/07/National-Dish-of-Germany-Sauerbraten.jpg?fit=1140%2C500&ssl=1',
    },
    {
        id: 5,
        name: 'Paella',
        price: 32,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'rice, seafood, chicken, saffron',
        img: 'https://www.tastingtable.com/img/gallery/the-uncertain-origin-of-scotlands-national-dish/l-intro-1658242590.jpg',
    },
    {
        id: 6,
        name: 'Hamburger',
        price: 20,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'bun, beef patty, lettuce, tomato, cheese',
        img: 'https://static.toiimg.com/thumb/msid-71723867/71723867.jpg?width=500&resizemode=4',
    },
]
export const EasternCuisine = [
    {
        id: 1,
        name: 'Sushi',
        price: 30,
        text: 'Delicious sushi rolls made with fresh fish and vegetables.',
        ingredients: ['rice', 'nori seaweed', 'fish', 'vegetables'],
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Mixed_Plate_%283186676853%29.jpg/1200px-Mixed_Plate_%283186676853%29.jpg',
    },
    {
        id: 2,
        name: 'Pad Thai',
        price: 25,
        text: 'A flavorful stir-fried noodle dish with a combination of ingredients.',
        ingredients: ['rice noodles', 'shrimp', 'tofu', 'bean sprouts', 'peanuts'],
        img: 'https://www.newarab.com/sites/default/files/media/images/98C3880A-E57D-4573-9385-C9130B977516.jpg',
    },
    {
        id: 3,
        name: 'Chicken Tikka Masala',
        price: 28,
        text: 'Tender chicken cooked in a creamy and spiced tomato-based sauce.',
        ingredients: ['chicken', 'yogurt', 'tomatoes', 'spices'],
        img: 'https://hummusbowls.com/wp-content/uploads/2019/12/Vegetarianism-and-Middle-Eastern-Cuisine-2-scaled.jpg',
    },
    {
        id: 4,
        name: 'Hummus',
        price: 12,
        text: 'A popular Middle Eastern dip made from chickpeas, tahini, and olive oil.',
        ingredients: ['chickpeas', 'tahini', 'olive oil', 'lemon juice'],
        img: 'https://www.chefspencil.com/wp-content/uploads/Shakshuka-960x960.png',
    },
    {
        id: 5,
        name: 'Biryani',
        price: 22,
        text: 'A flavorful rice dish with aromatic spices and meat or vegetables.',
        ingredients: ['rice', 'meat or vegetables', 'spices', 'saffron'],
        img: 'https://drifttravel.com/wp-content/uploads/2019/10/JA-Resorts-Hotel-Restaurant-1.jpg',
    },
    {
        id: 6,
        name: 'Miso Soup',
        price: 10,
        text: 'A traditional Japanese soup made with miso paste and various ingredients.',
        ingredients: ['miso paste', 'tofu', 'seaweed', 'green onions'],
        img: 'https://cdn.squaremeal.co.uk/restaurants/6664/eastern-cuisine-chicken.jpg?w=800',
    },
]
export const FastFoods = [
    {
        id: 1,
        name: 'Hamburger',
        price: 10,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'bun, beef patty, lettuce, tomato, cheese',
        img: 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-485610450-1522163314.jpg',
    },
    {
        id: 2,
        name: 'French Fries',
        price: 6,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'potatoes, salt, oil',
        img: 'https://www.fifteenspatulas.com/wp-content/uploads/2011/09/French-Fries-Recipe-500x500.jpg',
    },
    {
        id: 3,
        name: 'Pizza Slice',
        price: 8,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'dough, tomato sauce, cheese, toppings',
        img: 'https://www.mashed.com/img/gallery/this-is-the-most-nutritious-fast-food-pizza-you-can-buy/l-intro-1626224309.jpg',
    },
    {
        id: 4,
        name: 'Hot Dog',
        price: 7,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'hot dog bun, sausage, ketchup, mustard, onions',
        img: 'https://www.thedailymeal.com/img/gallery/ranking-12-fast-food-hot-dogs-from-worst-to-best/l-intro-1675120855.jpg',
    },
    {
        id: 5,
        name: 'Chicken Nuggets',
        price: 9,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'chicken meat, breadcrumbs, spices',
        img: 'https://www.seriouseats.com/thmb/xw1krLC9Yh85qx1wl5jw0BPCWHk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2015__07__20210324-SouthernFriedChicken-Andrew-Janjigian-21-cea1fe39234844638018b15259cabdc2.jpg',
    },
    {
        id: 6,
        name: 'Milkshake',
        price: 5,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        prescription: 'milk, ice cream, flavoring',
        img: 'https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/k%2FPhoto%2FRecipes%2F2020-07-how-to-make-a-milkshake-at-home%2F2020-06-08_AT-K19388',
    },
]